export const eventos = [
  {
    id: 1,
    image: "https://i.redd.it/3ccvjqsymii91.png",
    location: "Estadio Spotify Chinquihue",
    title: "Radiohead 1",
    description: "Concierto de la era Kid A — apertura con Everything In Its Right Place",
    date: "05 de Diciembre - 07 de Diciembre",
    price: "80.000",
  },
  {
    id: 2,
    image: "https://i.redd.it/3ccvjqsymii91.png",
    location: "Estadio Nacional - Ñuñoa",
    title: "Radiohead 2",
    description: "Setlist centrado en OK Computer y The Bends",
    date: "05 de Diciembre - 07 de Diciembre",
    price: "80.000",
  },
  {
    id: 3,
    image: "https://i.redd.it/3ccvjqsymii91.png",
    location: "Estadio Nacional - Ñuñoa",
    title: "Radiohead 3",
    description: "Presentación acústica con invitados especiales",
    date: "05 de Diciembre - 07 de Diciembre",
    price: "80.000",
  },
  {
    id: 4,
    image: "https://i.redd.it/3ccvjqsymii91.png",
    location: "Estadio Nacional - Ñuñoa",
    title: "Radiohead 4",
    description: "Concierto experimental con visuales inéditos",
    date: "05 de Diciembre - 07 de Diciembre",
    price: "80.000",
  },
  {
    id: 5,
    image: "https://i.redd.it/3ccvjqsymii91.png",
    location: "Estadio Nacional - Ñuñoa",
    title: "Radiohead 5",
    description: "Revisión completa de In Rainbows en vivo",
    date: "05 de Diciembre - 07 de Diciembre",
    price: "80.000",
  },
  {
    id: 6,
    image: "https://i.redd.it/3ccvjqsymii91.png",
    location: "Estadio Nacional - Ñuñoa",
    title: "Radiohead 6",
    description: "Show exclusivo para fanáticos con temas raros",
    date: "05 de Diciembre - 07 de Diciembre",
    price: "80.000",
  },
  {
    id: 7,
    image: "https://i.redd.it/3ccvjqsymii91.png",
    location: "Estadio Nacional - Ñuñoa",
    title: "Radiohead 7",
    description: "Tour especial celebrando 30 años de carrera",
    date: "05 de Diciembre - 07 de Diciembre",
    price: "80.000",
  },
  {
    id: 8,
    image: "https://i.redd.it/3ccvjqsymii91.png",
    location: "Estadio Nacional - Ñuñoa",
    title: "Radiohead 8",
    description: "Concierto de despedida en Chile",
    date: "05 de Diciembre - 07 de Diciembre",
    price: "80.000",
  },
];